USE Vendas;

CREATE TABLE tb_vendas (
    ID INT NOT NULL AUTO_INCREMENT,
    ID_NF INT NOT NULL,
    ID_ITEM INT NOT NULL,
    COD_PROD INT NOT NULL,
    VALOR_UNIT DECIMAL(5,2),
    QUANTIDADE INT,
    DESCONTO DECIMAL(5,2),
    PRIMARY KEY (ID)
)